#- name: Mysql setup
#  hosts: all
#  become: yes
#  tasks:
    - name: set hostname
      ansible.builtin.shell: set-hostname mysql

    - name: copy mysql repo file
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: disable mysql version8
      ansible.builtin.shell: dnf module disable mysql -y

    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    - name: Start Mysql
      ansible.builtin.systemd:
        name: mysqld
        state: restarted

    - name: set root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

    - name: install node exporter
      ansible.builtin.import_role:
        name: prometheus
        tasks_from: node-exporter

